/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.users.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import com.seam.api.types.AcsUser;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = UsersGetResponse.Builder.class)
public final class UsersGetResponse {
    private final AcsUser acsUser;

    private final boolean ok;

    private final Map<String, Object> additionalProperties;

    private UsersGetResponse(AcsUser acsUser, boolean ok, Map<String, Object> additionalProperties) {
        this.acsUser = acsUser;
        this.ok = ok;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("acs_user")
    public AcsUser getAcsUser() {
        return acsUser;
    }

    @JsonProperty("ok")
    public boolean getOk() {
        return ok;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UsersGetResponse && equalTo((UsersGetResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UsersGetResponse other) {
        return acsUser.equals(other.acsUser) && ok == other.ok;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.acsUser, this.ok);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AcsUserStage builder() {
        return new Builder();
    }

    public interface AcsUserStage {
        OkStage acsUser(AcsUser acsUser);

        Builder from(UsersGetResponse other);
    }

    public interface OkStage {
        _FinalStage ok(boolean ok);
    }

    public interface _FinalStage {
        UsersGetResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AcsUserStage, OkStage, _FinalStage {
        private AcsUser acsUser;

        private boolean ok;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UsersGetResponse other) {
            acsUser(other.getAcsUser());
            ok(other.getOk());
            return this;
        }

        @java.lang.Override
        @JsonSetter("acs_user")
        public OkStage acsUser(AcsUser acsUser) {
            this.acsUser = acsUser;
            return this;
        }

        @java.lang.Override
        @JsonSetter("ok")
        public _FinalStage ok(boolean ok) {
            this.ok = ok;
            return this;
        }

        @java.lang.Override
        public UsersGetResponse build() {
            return new UsersGetResponse(acsUser, ok, additionalProperties);
        }
    }
}
