/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.connectedaccounts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ConnectedAccountsDeleteRequest.Builder.class)
public final class ConnectedAccountsDeleteRequest {
    private final String connectedAccountId;

    private final Optional<Boolean> sync;

    private final Map<String, Object> additionalProperties;

    private ConnectedAccountsDeleteRequest(
            String connectedAccountId, Optional<Boolean> sync, Map<String, Object> additionalProperties) {
        this.connectedAccountId = connectedAccountId;
        this.sync = sync;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("connected_account_id")
    public String getConnectedAccountId() {
        return connectedAccountId;
    }

    @JsonProperty("sync")
    public Optional<Boolean> getSync() {
        return sync;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectedAccountsDeleteRequest && equalTo((ConnectedAccountsDeleteRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectedAccountsDeleteRequest other) {
        return connectedAccountId.equals(other.connectedAccountId) && sync.equals(other.sync);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.connectedAccountId, this.sync);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConnectedAccountIdStage builder() {
        return new Builder();
    }

    public interface ConnectedAccountIdStage {
        _FinalStage connectedAccountId(String connectedAccountId);

        Builder from(ConnectedAccountsDeleteRequest other);
    }

    public interface _FinalStage {
        ConnectedAccountsDeleteRequest build();

        _FinalStage sync(Optional<Boolean> sync);

        _FinalStage sync(Boolean sync);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConnectedAccountIdStage, _FinalStage {
        private String connectedAccountId;

        private Optional<Boolean> sync = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ConnectedAccountsDeleteRequest other) {
            connectedAccountId(other.getConnectedAccountId());
            sync(other.getSync());
            return this;
        }

        @Override
        @JsonSetter("connected_account_id")
        public _FinalStage connectedAccountId(String connectedAccountId) {
            this.connectedAccountId = connectedAccountId;
            return this;
        }

        @Override
        public _FinalStage sync(Boolean sync) {
            this.sync = Optional.of(sync);
            return this;
        }

        @Override
        @JsonSetter(value = "sync", nulls = Nulls.SKIP)
        public _FinalStage sync(Optional<Boolean> sync) {
            this.sync = sync;
            return this;
        }

        @Override
        public ConnectedAccountsDeleteRequest build() {
            return new ConnectedAccountsDeleteRequest(connectedAccountId, sync, additionalProperties);
        }
    }
}
