/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.connectedaccounts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import com.seam.api.resources.connectedaccounts.types.ConnectedAccountsUpdateRequestCustomMetadataValue;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ConnectedAccountsUpdateRequest.Builder.class)
public final class ConnectedAccountsUpdateRequest {
    private final String connectedAccountId;

    private final Optional<Boolean> automaticallyManageNewDevices;

    private final Optional<Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>>> customMetadata;

    private final Map<String, Object> additionalProperties;

    private ConnectedAccountsUpdateRequest(
            String connectedAccountId,
            Optional<Boolean> automaticallyManageNewDevices,
            Optional<Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>>> customMetadata,
            Map<String, Object> additionalProperties) {
        this.connectedAccountId = connectedAccountId;
        this.automaticallyManageNewDevices = automaticallyManageNewDevices;
        this.customMetadata = customMetadata;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("connected_account_id")
    public String getConnectedAccountId() {
        return connectedAccountId;
    }

    @JsonProperty("automatically_manage_new_devices")
    public Optional<Boolean> getAutomaticallyManageNewDevices() {
        return automaticallyManageNewDevices;
    }

    @JsonProperty("custom_metadata")
    public Optional<Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>>> getCustomMetadata() {
        return customMetadata;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectedAccountsUpdateRequest && equalTo((ConnectedAccountsUpdateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectedAccountsUpdateRequest other) {
        return connectedAccountId.equals(other.connectedAccountId)
                && automaticallyManageNewDevices.equals(other.automaticallyManageNewDevices)
                && customMetadata.equals(other.customMetadata);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.connectedAccountId, this.automaticallyManageNewDevices, this.customMetadata);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConnectedAccountIdStage builder() {
        return new Builder();
    }

    public interface ConnectedAccountIdStage {
        _FinalStage connectedAccountId(String connectedAccountId);

        Builder from(ConnectedAccountsUpdateRequest other);
    }

    public interface _FinalStage {
        ConnectedAccountsUpdateRequest build();

        _FinalStage automaticallyManageNewDevices(Optional<Boolean> automaticallyManageNewDevices);

        _FinalStage automaticallyManageNewDevices(Boolean automaticallyManageNewDevices);

        _FinalStage customMetadata(
                Optional<Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>>> customMetadata);

        _FinalStage customMetadata(
                Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>> customMetadata);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConnectedAccountIdStage, _FinalStage {
        private String connectedAccountId;

        private Optional<Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>>> customMetadata =
                Optional.empty();

        private Optional<Boolean> automaticallyManageNewDevices = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConnectedAccountsUpdateRequest other) {
            connectedAccountId(other.getConnectedAccountId());
            automaticallyManageNewDevices(other.getAutomaticallyManageNewDevices());
            customMetadata(other.getCustomMetadata());
            return this;
        }

        @java.lang.Override
        @JsonSetter("connected_account_id")
        public _FinalStage connectedAccountId(String connectedAccountId) {
            this.connectedAccountId = connectedAccountId;
            return this;
        }

        @java.lang.Override
        public _FinalStage customMetadata(
                Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>> customMetadata) {
            this.customMetadata = Optional.of(customMetadata);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "custom_metadata", nulls = Nulls.SKIP)
        public _FinalStage customMetadata(
                Optional<Map<String, Optional<ConnectedAccountsUpdateRequestCustomMetadataValue>>> customMetadata) {
            this.customMetadata = customMetadata;
            return this;
        }

        @java.lang.Override
        public _FinalStage automaticallyManageNewDevices(Boolean automaticallyManageNewDevices) {
            this.automaticallyManageNewDevices = Optional.of(automaticallyManageNewDevices);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "automatically_manage_new_devices", nulls = Nulls.SKIP)
        public _FinalStage automaticallyManageNewDevices(Optional<Boolean> automaticallyManageNewDevices) {
            this.automaticallyManageNewDevices = automaticallyManageNewDevices;
            return this;
        }

        @java.lang.Override
        public ConnectedAccountsUpdateRequest build() {
            return new ConnectedAccountsUpdateRequest(
                    connectedAccountId, automaticallyManageNewDevices, customMetadata, additionalProperties);
        }
    }
}
