/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.noisesensors.noisethresholds.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = NoiseThresholdsGetRequest.Builder.class)
public final class NoiseThresholdsGetRequest {
    private final String noiseThresholdId;

    private final Map<String, Object> additionalProperties;

    private NoiseThresholdsGetRequest(String noiseThresholdId, Map<String, Object> additionalProperties) {
        this.noiseThresholdId = noiseThresholdId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("noise_threshold_id")
    public String getNoiseThresholdId() {
        return noiseThresholdId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof NoiseThresholdsGetRequest && equalTo((NoiseThresholdsGetRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(NoiseThresholdsGetRequest other) {
        return noiseThresholdId.equals(other.noiseThresholdId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.noiseThresholdId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NoiseThresholdIdStage builder() {
        return new Builder();
    }

    public interface NoiseThresholdIdStage {
        _FinalStage noiseThresholdId(String noiseThresholdId);

        Builder from(NoiseThresholdsGetRequest other);
    }

    public interface _FinalStage {
        NoiseThresholdsGetRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NoiseThresholdIdStage, _FinalStage {
        private String noiseThresholdId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(NoiseThresholdsGetRequest other) {
            noiseThresholdId(other.getNoiseThresholdId());
            return this;
        }

        @Override
        @JsonSetter("noise_threshold_id")
        public _FinalStage noiseThresholdId(String noiseThresholdId) {
            this.noiseThresholdId = noiseThresholdId;
            return this;
        }

        @Override
        public NoiseThresholdsGetRequest build() {
            return new NoiseThresholdsGetRequest(noiseThresholdId, additionalProperties);
        }
    }
}
