/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.accessgroups.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = AccessGroupsGetRequest.Builder.class)
public final class AccessGroupsGetRequest {
    private final String acsAccessGroupId;

    private final Map<String, Object> additionalProperties;

    private AccessGroupsGetRequest(String acsAccessGroupId, Map<String, Object> additionalProperties) {
        this.acsAccessGroupId = acsAccessGroupId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("acs_access_group_id")
    public String getAcsAccessGroupId() {
        return acsAccessGroupId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AccessGroupsGetRequest && equalTo((AccessGroupsGetRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AccessGroupsGetRequest other) {
        return acsAccessGroupId.equals(other.acsAccessGroupId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.acsAccessGroupId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AcsAccessGroupIdStage builder() {
        return new Builder();
    }

    public interface AcsAccessGroupIdStage {
        _FinalStage acsAccessGroupId(String acsAccessGroupId);

        Builder from(AccessGroupsGetRequest other);
    }

    public interface _FinalStage {
        AccessGroupsGetRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AcsAccessGroupIdStage, _FinalStage {
        private String acsAccessGroupId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(AccessGroupsGetRequest other) {
            acsAccessGroupId(other.getAcsAccessGroupId());
            return this;
        }

        @Override
        @JsonSetter("acs_access_group_id")
        public _FinalStage acsAccessGroupId(String acsAccessGroupId) {
            this.acsAccessGroupId = acsAccessGroupId;
            return this;
        }

        @Override
        public AccessGroupsGetRequest build() {
            return new AccessGroupsGetRequest(acsAccessGroupId, additionalProperties);
        }
    }
}
