/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.clientsessions.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ClientSessionsCreateRequest.Builder.class)
public final class ClientSessionsCreateRequest {
    private final Optional<String> userIdentifierKey;

    private final Optional<List<String>> connectWebviewIds;

    private final Optional<List<String>> connectedAccountIds;

    private final Optional<List<String>> userIdentityIds;

    private final Optional<OffsetDateTime> expiresAt;

    private final Map<String, Object> additionalProperties;

    private ClientSessionsCreateRequest(
            Optional<String> userIdentifierKey,
            Optional<List<String>> connectWebviewIds,
            Optional<List<String>> connectedAccountIds,
            Optional<List<String>> userIdentityIds,
            Optional<OffsetDateTime> expiresAt,
            Map<String, Object> additionalProperties) {
        this.userIdentifierKey = userIdentifierKey;
        this.connectWebviewIds = connectWebviewIds;
        this.connectedAccountIds = connectedAccountIds;
        this.userIdentityIds = userIdentityIds;
        this.expiresAt = expiresAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("user_identifier_key")
    public Optional<String> getUserIdentifierKey() {
        return userIdentifierKey;
    }

    @JsonProperty("connect_webview_ids")
    public Optional<List<String>> getConnectWebviewIds() {
        return connectWebviewIds;
    }

    @JsonProperty("connected_account_ids")
    public Optional<List<String>> getConnectedAccountIds() {
        return connectedAccountIds;
    }

    @JsonProperty("user_identity_ids")
    public Optional<List<String>> getUserIdentityIds() {
        return userIdentityIds;
    }

    @JsonProperty("expires_at")
    public Optional<OffsetDateTime> getExpiresAt() {
        return expiresAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClientSessionsCreateRequest && equalTo((ClientSessionsCreateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClientSessionsCreateRequest other) {
        return userIdentifierKey.equals(other.userIdentifierKey)
                && connectWebviewIds.equals(other.connectWebviewIds)
                && connectedAccountIds.equals(other.connectedAccountIds)
                && userIdentityIds.equals(other.userIdentityIds)
                && expiresAt.equals(other.expiresAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.userIdentifierKey,
                this.connectWebviewIds,
                this.connectedAccountIds,
                this.userIdentityIds,
                this.expiresAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> userIdentifierKey = Optional.empty();

        private Optional<List<String>> connectWebviewIds = Optional.empty();

        private Optional<List<String>> connectedAccountIds = Optional.empty();

        private Optional<List<String>> userIdentityIds = Optional.empty();

        private Optional<OffsetDateTime> expiresAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ClientSessionsCreateRequest other) {
            userIdentifierKey(other.getUserIdentifierKey());
            connectWebviewIds(other.getConnectWebviewIds());
            connectedAccountIds(other.getConnectedAccountIds());
            userIdentityIds(other.getUserIdentityIds());
            expiresAt(other.getExpiresAt());
            return this;
        }

        @JsonSetter(value = "user_identifier_key", nulls = Nulls.SKIP)
        public Builder userIdentifierKey(Optional<String> userIdentifierKey) {
            this.userIdentifierKey = userIdentifierKey;
            return this;
        }

        public Builder userIdentifierKey(String userIdentifierKey) {
            this.userIdentifierKey = Optional.of(userIdentifierKey);
            return this;
        }

        @JsonSetter(value = "connect_webview_ids", nulls = Nulls.SKIP)
        public Builder connectWebviewIds(Optional<List<String>> connectWebviewIds) {
            this.connectWebviewIds = connectWebviewIds;
            return this;
        }

        public Builder connectWebviewIds(List<String> connectWebviewIds) {
            this.connectWebviewIds = Optional.of(connectWebviewIds);
            return this;
        }

        @JsonSetter(value = "connected_account_ids", nulls = Nulls.SKIP)
        public Builder connectedAccountIds(Optional<List<String>> connectedAccountIds) {
            this.connectedAccountIds = connectedAccountIds;
            return this;
        }

        public Builder connectedAccountIds(List<String> connectedAccountIds) {
            this.connectedAccountIds = Optional.of(connectedAccountIds);
            return this;
        }

        @JsonSetter(value = "user_identity_ids", nulls = Nulls.SKIP)
        public Builder userIdentityIds(Optional<List<String>> userIdentityIds) {
            this.userIdentityIds = userIdentityIds;
            return this;
        }

        public Builder userIdentityIds(List<String> userIdentityIds) {
            this.userIdentityIds = Optional.of(userIdentityIds);
            return this;
        }

        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public Builder expiresAt(Optional<OffsetDateTime> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        public Builder expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = Optional.of(expiresAt);
            return this;
        }

        public ClientSessionsCreateRequest build() {
            return new ClientSessionsCreateRequest(
                    userIdentifierKey,
                    connectWebviewIds,
                    connectedAccountIds,
                    userIdentityIds,
                    expiresAt,
                    additionalProperties);
        }
    }
}
