/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.clientsessions.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ClientSessionsRevokeRequest.Builder.class)
public final class ClientSessionsRevokeRequest {
    private final String clientSessionId;

    private final Map<String, Object> additionalProperties;

    private ClientSessionsRevokeRequest(String clientSessionId, Map<String, Object> additionalProperties) {
        this.clientSessionId = clientSessionId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("client_session_id")
    public String getClientSessionId() {
        return clientSessionId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClientSessionsRevokeRequest && equalTo((ClientSessionsRevokeRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClientSessionsRevokeRequest other) {
        return clientSessionId.equals(other.clientSessionId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.clientSessionId);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ClientSessionIdStage builder() {
        return new Builder();
    }

    public interface ClientSessionIdStage {
        _FinalStage clientSessionId(String clientSessionId);

        Builder from(ClientSessionsRevokeRequest other);
    }

    public interface _FinalStage {
        ClientSessionsRevokeRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ClientSessionIdStage, _FinalStage {
        private String clientSessionId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ClientSessionsRevokeRequest other) {
            clientSessionId(other.getClientSessionId());
            return this;
        }

        @Override
        @JsonSetter("client_session_id")
        public _FinalStage clientSessionId(String clientSessionId) {
            this.clientSessionId = clientSessionId;
            return this;
        }

        @Override
        public ClientSessionsRevokeRequest build() {
            return new ClientSessionsRevokeRequest(clientSessionId, additionalProperties);
        }
    }
}
