/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.accesscodes.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import com.seam.api.types.MaxTimeRounding;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = AccessCodesCreateRequest.Builder.class)
public final class AccessCodesCreateRequest {
    private final String deviceId;

    private final Optional<String> name;

    private final Optional<String> startsAt;

    private final Optional<String> endsAt;

    private final Optional<String> code;

    private final Optional<Boolean> sync;

    private final Optional<Boolean> attemptForOfflineDevice;

    private final Optional<String> commonCodeKey;

    private final Optional<Boolean> preferNativeScheduling;

    private final Optional<Boolean> useBackupAccessCodePool;

    private final Optional<Boolean> allowExternalModification;

    private final Optional<Boolean> isExternalModificationAllowed;

    private final Optional<Boolean> useOfflineAccessCode;

    private final Optional<Boolean> isOfflineAccessCode;

    private final Optional<Boolean> isOneTimeUse;

    private final Optional<MaxTimeRounding> maxTimeRounding;

    private final Map<String, Object> additionalProperties;

    private AccessCodesCreateRequest(
            String deviceId,
            Optional<String> name,
            Optional<String> startsAt,
            Optional<String> endsAt,
            Optional<String> code,
            Optional<Boolean> sync,
            Optional<Boolean> attemptForOfflineDevice,
            Optional<String> commonCodeKey,
            Optional<Boolean> preferNativeScheduling,
            Optional<Boolean> useBackupAccessCodePool,
            Optional<Boolean> allowExternalModification,
            Optional<Boolean> isExternalModificationAllowed,
            Optional<Boolean> useOfflineAccessCode,
            Optional<Boolean> isOfflineAccessCode,
            Optional<Boolean> isOneTimeUse,
            Optional<MaxTimeRounding> maxTimeRounding,
            Map<String, Object> additionalProperties) {
        this.deviceId = deviceId;
        this.name = name;
        this.startsAt = startsAt;
        this.endsAt = endsAt;
        this.code = code;
        this.sync = sync;
        this.attemptForOfflineDevice = attemptForOfflineDevice;
        this.commonCodeKey = commonCodeKey;
        this.preferNativeScheduling = preferNativeScheduling;
        this.useBackupAccessCodePool = useBackupAccessCodePool;
        this.allowExternalModification = allowExternalModification;
        this.isExternalModificationAllowed = isExternalModificationAllowed;
        this.useOfflineAccessCode = useOfflineAccessCode;
        this.isOfflineAccessCode = isOfflineAccessCode;
        this.isOneTimeUse = isOneTimeUse;
        this.maxTimeRounding = maxTimeRounding;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("device_id")
    public String getDeviceId() {
        return deviceId;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("starts_at")
    public Optional<String> getStartsAt() {
        return startsAt;
    }

    @JsonProperty("ends_at")
    public Optional<String> getEndsAt() {
        return endsAt;
    }

    @JsonProperty("code")
    public Optional<String> getCode() {
        return code;
    }

    @JsonProperty("sync")
    public Optional<Boolean> getSync() {
        return sync;
    }

    @JsonProperty("attempt_for_offline_device")
    public Optional<Boolean> getAttemptForOfflineDevice() {
        return attemptForOfflineDevice;
    }

    @JsonProperty("common_code_key")
    public Optional<String> getCommonCodeKey() {
        return commonCodeKey;
    }

    @JsonProperty("prefer_native_scheduling")
    public Optional<Boolean> getPreferNativeScheduling() {
        return preferNativeScheduling;
    }

    @JsonProperty("use_backup_access_code_pool")
    public Optional<Boolean> getUseBackupAccessCodePool() {
        return useBackupAccessCodePool;
    }

    @JsonProperty("allow_external_modification")
    public Optional<Boolean> getAllowExternalModification() {
        return allowExternalModification;
    }

    @JsonProperty("is_external_modification_allowed")
    public Optional<Boolean> getIsExternalModificationAllowed() {
        return isExternalModificationAllowed;
    }

    @JsonProperty("use_offline_access_code")
    public Optional<Boolean> getUseOfflineAccessCode() {
        return useOfflineAccessCode;
    }

    @JsonProperty("is_offline_access_code")
    public Optional<Boolean> getIsOfflineAccessCode() {
        return isOfflineAccessCode;
    }

    @JsonProperty("is_one_time_use")
    public Optional<Boolean> getIsOneTimeUse() {
        return isOneTimeUse;
    }

    @JsonProperty("max_time_rounding")
    public Optional<MaxTimeRounding> getMaxTimeRounding() {
        return maxTimeRounding;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AccessCodesCreateRequest && equalTo((AccessCodesCreateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AccessCodesCreateRequest other) {
        return deviceId.equals(other.deviceId)
                && name.equals(other.name)
                && startsAt.equals(other.startsAt)
                && endsAt.equals(other.endsAt)
                && code.equals(other.code)
                && sync.equals(other.sync)
                && attemptForOfflineDevice.equals(other.attemptForOfflineDevice)
                && commonCodeKey.equals(other.commonCodeKey)
                && preferNativeScheduling.equals(other.preferNativeScheduling)
                && useBackupAccessCodePool.equals(other.useBackupAccessCodePool)
                && allowExternalModification.equals(other.allowExternalModification)
                && isExternalModificationAllowed.equals(other.isExternalModificationAllowed)
                && useOfflineAccessCode.equals(other.useOfflineAccessCode)
                && isOfflineAccessCode.equals(other.isOfflineAccessCode)
                && isOneTimeUse.equals(other.isOneTimeUse)
                && maxTimeRounding.equals(other.maxTimeRounding);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.deviceId,
                this.name,
                this.startsAt,
                this.endsAt,
                this.code,
                this.sync,
                this.attemptForOfflineDevice,
                this.commonCodeKey,
                this.preferNativeScheduling,
                this.useBackupAccessCodePool,
                this.allowExternalModification,
                this.isExternalModificationAllowed,
                this.useOfflineAccessCode,
                this.isOfflineAccessCode,
                this.isOneTimeUse,
                this.maxTimeRounding);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DeviceIdStage builder() {
        return new Builder();
    }

    public interface DeviceIdStage {
        _FinalStage deviceId(String deviceId);

        Builder from(AccessCodesCreateRequest other);
    }

    public interface _FinalStage {
        AccessCodesCreateRequest build();

        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        _FinalStage startsAt(Optional<String> startsAt);

        _FinalStage startsAt(String startsAt);

        _FinalStage endsAt(Optional<String> endsAt);

        _FinalStage endsAt(String endsAt);

        _FinalStage code(Optional<String> code);

        _FinalStage code(String code);

        _FinalStage sync(Optional<Boolean> sync);

        _FinalStage sync(Boolean sync);

        _FinalStage attemptForOfflineDevice(Optional<Boolean> attemptForOfflineDevice);

        _FinalStage attemptForOfflineDevice(Boolean attemptForOfflineDevice);

        _FinalStage commonCodeKey(Optional<String> commonCodeKey);

        _FinalStage commonCodeKey(String commonCodeKey);

        _FinalStage preferNativeScheduling(Optional<Boolean> preferNativeScheduling);

        _FinalStage preferNativeScheduling(Boolean preferNativeScheduling);

        _FinalStage useBackupAccessCodePool(Optional<Boolean> useBackupAccessCodePool);

        _FinalStage useBackupAccessCodePool(Boolean useBackupAccessCodePool);

        _FinalStage allowExternalModification(Optional<Boolean> allowExternalModification);

        _FinalStage allowExternalModification(Boolean allowExternalModification);

        _FinalStage isExternalModificationAllowed(Optional<Boolean> isExternalModificationAllowed);

        _FinalStage isExternalModificationAllowed(Boolean isExternalModificationAllowed);

        _FinalStage useOfflineAccessCode(Optional<Boolean> useOfflineAccessCode);

        _FinalStage useOfflineAccessCode(Boolean useOfflineAccessCode);

        _FinalStage isOfflineAccessCode(Optional<Boolean> isOfflineAccessCode);

        _FinalStage isOfflineAccessCode(Boolean isOfflineAccessCode);

        _FinalStage isOneTimeUse(Optional<Boolean> isOneTimeUse);

        _FinalStage isOneTimeUse(Boolean isOneTimeUse);

        _FinalStage maxTimeRounding(Optional<MaxTimeRounding> maxTimeRounding);

        _FinalStage maxTimeRounding(MaxTimeRounding maxTimeRounding);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DeviceIdStage, _FinalStage {
        private String deviceId;

        private Optional<MaxTimeRounding> maxTimeRounding = Optional.empty();

        private Optional<Boolean> isOneTimeUse = Optional.empty();

        private Optional<Boolean> isOfflineAccessCode = Optional.empty();

        private Optional<Boolean> useOfflineAccessCode = Optional.empty();

        private Optional<Boolean> isExternalModificationAllowed = Optional.empty();

        private Optional<Boolean> allowExternalModification = Optional.empty();

        private Optional<Boolean> useBackupAccessCodePool = Optional.empty();

        private Optional<Boolean> preferNativeScheduling = Optional.empty();

        private Optional<String> commonCodeKey = Optional.empty();

        private Optional<Boolean> attemptForOfflineDevice = Optional.empty();

        private Optional<Boolean> sync = Optional.empty();

        private Optional<String> code = Optional.empty();

        private Optional<String> endsAt = Optional.empty();

        private Optional<String> startsAt = Optional.empty();

        private Optional<String> name = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AccessCodesCreateRequest other) {
            deviceId(other.getDeviceId());
            name(other.getName());
            startsAt(other.getStartsAt());
            endsAt(other.getEndsAt());
            code(other.getCode());
            sync(other.getSync());
            attemptForOfflineDevice(other.getAttemptForOfflineDevice());
            commonCodeKey(other.getCommonCodeKey());
            preferNativeScheduling(other.getPreferNativeScheduling());
            useBackupAccessCodePool(other.getUseBackupAccessCodePool());
            allowExternalModification(other.getAllowExternalModification());
            isExternalModificationAllowed(other.getIsExternalModificationAllowed());
            useOfflineAccessCode(other.getUseOfflineAccessCode());
            isOfflineAccessCode(other.getIsOfflineAccessCode());
            isOneTimeUse(other.getIsOneTimeUse());
            maxTimeRounding(other.getMaxTimeRounding());
            return this;
        }

        @java.lang.Override
        @JsonSetter("device_id")
        public _FinalStage deviceId(String deviceId) {
            this.deviceId = deviceId;
            return this;
        }

        @java.lang.Override
        public _FinalStage maxTimeRounding(MaxTimeRounding maxTimeRounding) {
            this.maxTimeRounding = Optional.of(maxTimeRounding);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "max_time_rounding", nulls = Nulls.SKIP)
        public _FinalStage maxTimeRounding(Optional<MaxTimeRounding> maxTimeRounding) {
            this.maxTimeRounding = maxTimeRounding;
            return this;
        }

        @java.lang.Override
        public _FinalStage isOneTimeUse(Boolean isOneTimeUse) {
            this.isOneTimeUse = Optional.of(isOneTimeUse);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "is_one_time_use", nulls = Nulls.SKIP)
        public _FinalStage isOneTimeUse(Optional<Boolean> isOneTimeUse) {
            this.isOneTimeUse = isOneTimeUse;
            return this;
        }

        @java.lang.Override
        public _FinalStage isOfflineAccessCode(Boolean isOfflineAccessCode) {
            this.isOfflineAccessCode = Optional.of(isOfflineAccessCode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "is_offline_access_code", nulls = Nulls.SKIP)
        public _FinalStage isOfflineAccessCode(Optional<Boolean> isOfflineAccessCode) {
            this.isOfflineAccessCode = isOfflineAccessCode;
            return this;
        }

        @java.lang.Override
        public _FinalStage useOfflineAccessCode(Boolean useOfflineAccessCode) {
            this.useOfflineAccessCode = Optional.of(useOfflineAccessCode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "use_offline_access_code", nulls = Nulls.SKIP)
        public _FinalStage useOfflineAccessCode(Optional<Boolean> useOfflineAccessCode) {
            this.useOfflineAccessCode = useOfflineAccessCode;
            return this;
        }

        @java.lang.Override
        public _FinalStage isExternalModificationAllowed(Boolean isExternalModificationAllowed) {
            this.isExternalModificationAllowed = Optional.of(isExternalModificationAllowed);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "is_external_modification_allowed", nulls = Nulls.SKIP)
        public _FinalStage isExternalModificationAllowed(Optional<Boolean> isExternalModificationAllowed) {
            this.isExternalModificationAllowed = isExternalModificationAllowed;
            return this;
        }

        @java.lang.Override
        public _FinalStage allowExternalModification(Boolean allowExternalModification) {
            this.allowExternalModification = Optional.of(allowExternalModification);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "allow_external_modification", nulls = Nulls.SKIP)
        public _FinalStage allowExternalModification(Optional<Boolean> allowExternalModification) {
            this.allowExternalModification = allowExternalModification;
            return this;
        }

        @java.lang.Override
        public _FinalStage useBackupAccessCodePool(Boolean useBackupAccessCodePool) {
            this.useBackupAccessCodePool = Optional.of(useBackupAccessCodePool);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "use_backup_access_code_pool", nulls = Nulls.SKIP)
        public _FinalStage useBackupAccessCodePool(Optional<Boolean> useBackupAccessCodePool) {
            this.useBackupAccessCodePool = useBackupAccessCodePool;
            return this;
        }

        @java.lang.Override
        public _FinalStage preferNativeScheduling(Boolean preferNativeScheduling) {
            this.preferNativeScheduling = Optional.of(preferNativeScheduling);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "prefer_native_scheduling", nulls = Nulls.SKIP)
        public _FinalStage preferNativeScheduling(Optional<Boolean> preferNativeScheduling) {
            this.preferNativeScheduling = preferNativeScheduling;
            return this;
        }

        @java.lang.Override
        public _FinalStage commonCodeKey(String commonCodeKey) {
            this.commonCodeKey = Optional.of(commonCodeKey);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "common_code_key", nulls = Nulls.SKIP)
        public _FinalStage commonCodeKey(Optional<String> commonCodeKey) {
            this.commonCodeKey = commonCodeKey;
            return this;
        }

        @java.lang.Override
        public _FinalStage attemptForOfflineDevice(Boolean attemptForOfflineDevice) {
            this.attemptForOfflineDevice = Optional.of(attemptForOfflineDevice);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "attempt_for_offline_device", nulls = Nulls.SKIP)
        public _FinalStage attemptForOfflineDevice(Optional<Boolean> attemptForOfflineDevice) {
            this.attemptForOfflineDevice = attemptForOfflineDevice;
            return this;
        }

        @java.lang.Override
        public _FinalStage sync(Boolean sync) {
            this.sync = Optional.of(sync);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "sync", nulls = Nulls.SKIP)
        public _FinalStage sync(Optional<Boolean> sync) {
            this.sync = sync;
            return this;
        }

        @java.lang.Override
        public _FinalStage code(String code) {
            this.code = Optional.of(code);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "code", nulls = Nulls.SKIP)
        public _FinalStage code(Optional<String> code) {
            this.code = code;
            return this;
        }

        @java.lang.Override
        public _FinalStage endsAt(String endsAt) {
            this.endsAt = Optional.of(endsAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "ends_at", nulls = Nulls.SKIP)
        public _FinalStage endsAt(Optional<String> endsAt) {
            this.endsAt = endsAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage startsAt(String startsAt) {
            this.startsAt = Optional.of(startsAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "starts_at", nulls = Nulls.SKIP)
        public _FinalStage startsAt(Optional<String> startsAt) {
            this.startsAt = startsAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.of(name);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public AccessCodesCreateRequest build() {
            return new AccessCodesCreateRequest(
                    deviceId,
                    name,
                    startsAt,
                    endsAt,
                    code,
                    sync,
                    attemptForOfflineDevice,
                    commonCodeKey,
                    preferNativeScheduling,
                    useBackupAccessCodePool,
                    allowExternalModification,
                    isExternalModificationAllowed,
                    useOfflineAccessCode,
                    isOfflineAccessCode,
                    isOneTimeUse,
                    maxTimeRounding,
                    additionalProperties);
        }
    }
}
