/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.accesscodes.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = AccessCodesPullBackupAccessCodeRequest.Builder.class)
public final class AccessCodesPullBackupAccessCodeRequest {
    private final String accessCodeId;

    private final Map<String, Object> additionalProperties;

    private AccessCodesPullBackupAccessCodeRequest(String accessCodeId, Map<String, Object> additionalProperties) {
        this.accessCodeId = accessCodeId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("access_code_id")
    public String getAccessCodeId() {
        return accessCodeId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AccessCodesPullBackupAccessCodeRequest
                && equalTo((AccessCodesPullBackupAccessCodeRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AccessCodesPullBackupAccessCodeRequest other) {
        return accessCodeId.equals(other.accessCodeId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accessCodeId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccessCodeIdStage builder() {
        return new Builder();
    }

    public interface AccessCodeIdStage {
        _FinalStage accessCodeId(String accessCodeId);

        Builder from(AccessCodesPullBackupAccessCodeRequest other);
    }

    public interface _FinalStage {
        AccessCodesPullBackupAccessCodeRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AccessCodeIdStage, _FinalStage {
        private String accessCodeId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AccessCodesPullBackupAccessCodeRequest other) {
            accessCodeId(other.getAccessCodeId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("access_code_id")
        public _FinalStage accessCodeId(String accessCodeId) {
            this.accessCodeId = accessCodeId;
            return this;
        }

        @java.lang.Override
        public AccessCodesPullBackupAccessCodeRequest build() {
            return new AccessCodesPullBackupAccessCodeRequest(accessCodeId, additionalProperties);
        }
    }
}
