/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.users.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = UsersListAccessibleEntrancesRequest.Builder.class)
public final class UsersListAccessibleEntrancesRequest {
    private final String acsUserId;

    private final Map<String, Object> additionalProperties;

    private UsersListAccessibleEntrancesRequest(String acsUserId, Map<String, Object> additionalProperties) {
        this.acsUserId = acsUserId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("acs_user_id")
    public String getAcsUserId() {
        return acsUserId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UsersListAccessibleEntrancesRequest
                && equalTo((UsersListAccessibleEntrancesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UsersListAccessibleEntrancesRequest other) {
        return acsUserId.equals(other.acsUserId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.acsUserId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AcsUserIdStage builder() {
        return new Builder();
    }

    public interface AcsUserIdStage {
        _FinalStage acsUserId(String acsUserId);

        Builder from(UsersListAccessibleEntrancesRequest other);
    }

    public interface _FinalStage {
        UsersListAccessibleEntrancesRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AcsUserIdStage, _FinalStage {
        private String acsUserId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UsersListAccessibleEntrancesRequest other) {
            acsUserId(other.getAcsUserId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("acs_user_id")
        public _FinalStage acsUserId(String acsUserId) {
            this.acsUserId = acsUserId;
            return this;
        }

        @java.lang.Override
        public UsersListAccessibleEntrancesRequest build() {
            return new UsersListAccessibleEntrancesRequest(acsUserId, additionalProperties);
        }
    }
}
