/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.users.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = UsersRemoveFromAccessGroupRequest.Builder.class)
public final class UsersRemoveFromAccessGroupRequest {
    private final String acsUserId;

    private final String acsAccessGroupId;

    private final Map<String, Object> additionalProperties;

    private UsersRemoveFromAccessGroupRequest(
            String acsUserId, String acsAccessGroupId, Map<String, Object> additionalProperties) {
        this.acsUserId = acsUserId;
        this.acsAccessGroupId = acsAccessGroupId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("acs_user_id")
    public String getAcsUserId() {
        return acsUserId;
    }

    @JsonProperty("acs_access_group_id")
    public String getAcsAccessGroupId() {
        return acsAccessGroupId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UsersRemoveFromAccessGroupRequest && equalTo((UsersRemoveFromAccessGroupRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UsersRemoveFromAccessGroupRequest other) {
        return acsUserId.equals(other.acsUserId) && acsAccessGroupId.equals(other.acsAccessGroupId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.acsUserId, this.acsAccessGroupId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AcsUserIdStage builder() {
        return new Builder();
    }

    public interface AcsUserIdStage {
        AcsAccessGroupIdStage acsUserId(String acsUserId);

        Builder from(UsersRemoveFromAccessGroupRequest other);
    }

    public interface AcsAccessGroupIdStage {
        _FinalStage acsAccessGroupId(String acsAccessGroupId);
    }

    public interface _FinalStage {
        UsersRemoveFromAccessGroupRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AcsUserIdStage, AcsAccessGroupIdStage, _FinalStage {
        private String acsUserId;

        private String acsAccessGroupId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UsersRemoveFromAccessGroupRequest other) {
            acsUserId(other.getAcsUserId());
            acsAccessGroupId(other.getAcsAccessGroupId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("acs_user_id")
        public AcsAccessGroupIdStage acsUserId(String acsUserId) {
            this.acsUserId = acsUserId;
            return this;
        }

        @java.lang.Override
        @JsonSetter("acs_access_group_id")
        public _FinalStage acsAccessGroupId(String acsAccessGroupId) {
            this.acsAccessGroupId = acsAccessGroupId;
            return this;
        }

        @java.lang.Override
        public UsersRemoveFromAccessGroupRequest build() {
            return new UsersRemoveFromAccessGroupRequest(acsUserId, acsAccessGroupId, additionalProperties);
        }
    }
}
