/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AcsEntranceVisionlineMetadataProfilesItemVisionlineDoorProfileType {
    BLE("BLE"),

    COMMON_DOOR("commonDoor"),

    TOUCH("touch");

    private final String value;

    AcsEntranceVisionlineMetadataProfilesItemVisionlineDoorProfileType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
