/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = DevicePropertiesGenieMetadata.Builder.class)
public final class DevicePropertiesGenieMetadata {
    private final String deviceName;

    private final String doorName;

    private final Map<String, Object> additionalProperties;

    private DevicePropertiesGenieMetadata(
            String deviceName, String doorName, Map<String, Object> additionalProperties) {
        this.deviceName = deviceName;
        this.doorName = doorName;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("device_name")
    public String getDeviceName() {
        return deviceName;
    }

    @JsonProperty("door_name")
    public String getDoorName() {
        return doorName;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DevicePropertiesGenieMetadata && equalTo((DevicePropertiesGenieMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DevicePropertiesGenieMetadata other) {
        return deviceName.equals(other.deviceName) && doorName.equals(other.doorName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.deviceName, this.doorName);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DeviceNameStage builder() {
        return new Builder();
    }

    public interface DeviceNameStage {
        DoorNameStage deviceName(String deviceName);

        Builder from(DevicePropertiesGenieMetadata other);
    }

    public interface DoorNameStage {
        _FinalStage doorName(String doorName);
    }

    public interface _FinalStage {
        DevicePropertiesGenieMetadata build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DeviceNameStage, DoorNameStage, _FinalStage {
        private String deviceName;

        private String doorName;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(DevicePropertiesGenieMetadata other) {
            deviceName(other.getDeviceName());
            doorName(other.getDoorName());
            return this;
        }

        @Override
        @JsonSetter("device_name")
        public DoorNameStage deviceName(String deviceName) {
            this.deviceName = deviceName;
            return this;
        }

        @Override
        @JsonSetter("door_name")
        public _FinalStage doorName(String doorName) {
            this.doorName = doorName;
            return this;
        }

        @Override
        public DevicePropertiesGenieMetadata build() {
            return new DevicePropertiesGenieMetadata(deviceName, doorName, additionalProperties);
        }
    }
}
