/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = DevicePropertiesWyzeMetadata.Builder.class)
public final class DevicePropertiesWyzeMetadata {
    private final String deviceId;

    private final String deviceName;

    private final String productName;

    private final String productType;

    private final String productModel;

    private final String deviceInfoModel;

    private final Optional<String> keypadUuid;

    private final Optional<Double> lockerStatusHardlock;

    private final Map<String, Object> additionalProperties;

    private DevicePropertiesWyzeMetadata(
            String deviceId,
            String deviceName,
            String productName,
            String productType,
            String productModel,
            String deviceInfoModel,
            Optional<String> keypadUuid,
            Optional<Double> lockerStatusHardlock,
            Map<String, Object> additionalProperties) {
        this.deviceId = deviceId;
        this.deviceName = deviceName;
        this.productName = productName;
        this.productType = productType;
        this.productModel = productModel;
        this.deviceInfoModel = deviceInfoModel;
        this.keypadUuid = keypadUuid;
        this.lockerStatusHardlock = lockerStatusHardlock;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("device_id")
    public String getDeviceId() {
        return deviceId;
    }

    @JsonProperty("device_name")
    public String getDeviceName() {
        return deviceName;
    }

    @JsonProperty("product_name")
    public String getProductName() {
        return productName;
    }

    @JsonProperty("product_type")
    public String getProductType() {
        return productType;
    }

    @JsonProperty("product_model")
    public String getProductModel() {
        return productModel;
    }

    @JsonProperty("device_info_model")
    public String getDeviceInfoModel() {
        return deviceInfoModel;
    }

    @JsonProperty("keypad_uuid")
    public Optional<String> getKeypadUuid() {
        return keypadUuid;
    }

    @JsonProperty("locker_status_hardlock")
    public Optional<Double> getLockerStatusHardlock() {
        return lockerStatusHardlock;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DevicePropertiesWyzeMetadata && equalTo((DevicePropertiesWyzeMetadata) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DevicePropertiesWyzeMetadata other) {
        return deviceId.equals(other.deviceId)
                && deviceName.equals(other.deviceName)
                && productName.equals(other.productName)
                && productType.equals(other.productType)
                && productModel.equals(other.productModel)
                && deviceInfoModel.equals(other.deviceInfoModel)
                && keypadUuid.equals(other.keypadUuid)
                && lockerStatusHardlock.equals(other.lockerStatusHardlock);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.deviceId,
                this.deviceName,
                this.productName,
                this.productType,
                this.productModel,
                this.deviceInfoModel,
                this.keypadUuid,
                this.lockerStatusHardlock);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DeviceIdStage builder() {
        return new Builder();
    }

    public interface DeviceIdStage {
        DeviceNameStage deviceId(String deviceId);

        Builder from(DevicePropertiesWyzeMetadata other);
    }

    public interface DeviceNameStage {
        ProductNameStage deviceName(String deviceName);
    }

    public interface ProductNameStage {
        ProductTypeStage productName(String productName);
    }

    public interface ProductTypeStage {
        ProductModelStage productType(String productType);
    }

    public interface ProductModelStage {
        DeviceInfoModelStage productModel(String productModel);
    }

    public interface DeviceInfoModelStage {
        _FinalStage deviceInfoModel(String deviceInfoModel);
    }

    public interface _FinalStage {
        DevicePropertiesWyzeMetadata build();

        _FinalStage keypadUuid(Optional<String> keypadUuid);

        _FinalStage keypadUuid(String keypadUuid);

        _FinalStage lockerStatusHardlock(Optional<Double> lockerStatusHardlock);

        _FinalStage lockerStatusHardlock(Double lockerStatusHardlock);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements DeviceIdStage,
                    DeviceNameStage,
                    ProductNameStage,
                    ProductTypeStage,
                    ProductModelStage,
                    DeviceInfoModelStage,
                    _FinalStage {
        private String deviceId;

        private String deviceName;

        private String productName;

        private String productType;

        private String productModel;

        private String deviceInfoModel;

        private Optional<Double> lockerStatusHardlock = Optional.empty();

        private Optional<String> keypadUuid = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(DevicePropertiesWyzeMetadata other) {
            deviceId(other.getDeviceId());
            deviceName(other.getDeviceName());
            productName(other.getProductName());
            productType(other.getProductType());
            productModel(other.getProductModel());
            deviceInfoModel(other.getDeviceInfoModel());
            keypadUuid(other.getKeypadUuid());
            lockerStatusHardlock(other.getLockerStatusHardlock());
            return this;
        }

        @Override
        @JsonSetter("device_id")
        public DeviceNameStage deviceId(String deviceId) {
            this.deviceId = deviceId;
            return this;
        }

        @Override
        @JsonSetter("device_name")
        public ProductNameStage deviceName(String deviceName) {
            this.deviceName = deviceName;
            return this;
        }

        @Override
        @JsonSetter("product_name")
        public ProductTypeStage productName(String productName) {
            this.productName = productName;
            return this;
        }

        @Override
        @JsonSetter("product_type")
        public ProductModelStage productType(String productType) {
            this.productType = productType;
            return this;
        }

        @Override
        @JsonSetter("product_model")
        public DeviceInfoModelStage productModel(String productModel) {
            this.productModel = productModel;
            return this;
        }

        @Override
        @JsonSetter("device_info_model")
        public _FinalStage deviceInfoModel(String deviceInfoModel) {
            this.deviceInfoModel = deviceInfoModel;
            return this;
        }

        @Override
        public _FinalStage lockerStatusHardlock(Double lockerStatusHardlock) {
            this.lockerStatusHardlock = Optional.of(lockerStatusHardlock);
            return this;
        }

        @Override
        @JsonSetter(value = "locker_status_hardlock", nulls = Nulls.SKIP)
        public _FinalStage lockerStatusHardlock(Optional<Double> lockerStatusHardlock) {
            this.lockerStatusHardlock = lockerStatusHardlock;
            return this;
        }

        @Override
        public _FinalStage keypadUuid(String keypadUuid) {
            this.keypadUuid = Optional.of(keypadUuid);
            return this;
        }

        @Override
        @JsonSetter(value = "keypad_uuid", nulls = Nulls.SKIP)
        public _FinalStage keypadUuid(Optional<String> keypadUuid) {
            this.keypadUuid = keypadUuid;
            return this;
        }

        @Override
        public DevicePropertiesWyzeMetadata build() {
            return new DevicePropertiesWyzeMetadata(
                    deviceId,
                    deviceName,
                    productName,
                    productType,
                    productModel,
                    deviceInfoModel,
                    keypadUuid,
                    lockerStatusHardlock,
                    additionalProperties);
        }
    }
}
