/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = UnmanagedDeviceDeviceProvider.Builder.class)
public final class UnmanagedDeviceDeviceProvider {
    private final Optional<Object> providerCategories;

    private final Map<String, Object> additionalProperties;

    private UnmanagedDeviceDeviceProvider(
            Optional<Object> providerCategories, Map<String, Object> additionalProperties) {
        this.providerCategories = providerCategories;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("provider_categories")
    public Optional<Object> getProviderCategories() {
        return providerCategories;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UnmanagedDeviceDeviceProvider && equalTo((UnmanagedDeviceDeviceProvider) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UnmanagedDeviceDeviceProvider other) {
        return providerCategories.equals(other.providerCategories);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.providerCategories);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Object> providerCategories = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UnmanagedDeviceDeviceProvider other) {
            providerCategories(other.getProviderCategories());
            return this;
        }

        @JsonSetter(value = "provider_categories", nulls = Nulls.SKIP)
        public Builder providerCategories(Optional<Object> providerCategories) {
            this.providerCategories = providerCategories;
            return this;
        }

        public Builder providerCategories(Object providerCategories) {
            this.providerCategories = Optional.of(providerCategories);
            return this;
        }

        public UnmanagedDeviceDeviceProvider build() {
            return new UnmanagedDeviceDeviceProvider(providerCategories, additionalProperties);
        }
    }
}
