/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = Workspace.Builder.class)
public final class Workspace {
    private final String workspaceId;

    private final String name;

    private final String companyName;

    private final boolean isSandbox;

    private final Optional<String> connectPartnerName;

    private final Map<String, Object> additionalProperties;

    private Workspace(
            String workspaceId,
            String name,
            String companyName,
            boolean isSandbox,
            Optional<String> connectPartnerName,
            Map<String, Object> additionalProperties) {
        this.workspaceId = workspaceId;
        this.name = name;
        this.companyName = companyName;
        this.isSandbox = isSandbox;
        this.connectPartnerName = connectPartnerName;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("workspace_id")
    public String getWorkspaceId() {
        return workspaceId;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("company_name")
    public String getCompanyName() {
        return companyName;
    }

    @JsonProperty("is_sandbox")
    public boolean getIsSandbox() {
        return isSandbox;
    }

    /**
     * @return <hr />
     * <pre><code>deprecated: use company_name
     * ---
     * </code></pre>
     */
    @JsonProperty("connect_partner_name")
    public Optional<String> getConnectPartnerName() {
        return connectPartnerName;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Workspace && equalTo((Workspace) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Workspace other) {
        return workspaceId.equals(other.workspaceId)
                && name.equals(other.name)
                && companyName.equals(other.companyName)
                && isSandbox == other.isSandbox
                && connectPartnerName.equals(other.connectPartnerName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.workspaceId, this.name, this.companyName, this.isSandbox, this.connectPartnerName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static WorkspaceIdStage builder() {
        return new Builder();
    }

    public interface WorkspaceIdStage {
        NameStage workspaceId(String workspaceId);

        Builder from(Workspace other);
    }

    public interface NameStage {
        CompanyNameStage name(String name);
    }

    public interface CompanyNameStage {
        IsSandboxStage companyName(String companyName);
    }

    public interface IsSandboxStage {
        _FinalStage isSandbox(boolean isSandbox);
    }

    public interface _FinalStage {
        Workspace build();

        _FinalStage connectPartnerName(Optional<String> connectPartnerName);

        _FinalStage connectPartnerName(String connectPartnerName);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements WorkspaceIdStage, NameStage, CompanyNameStage, IsSandboxStage, _FinalStage {
        private String workspaceId;

        private String name;

        private String companyName;

        private boolean isSandbox;

        private Optional<String> connectPartnerName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Workspace other) {
            workspaceId(other.getWorkspaceId());
            name(other.getName());
            companyName(other.getCompanyName());
            isSandbox(other.getIsSandbox());
            connectPartnerName(other.getConnectPartnerName());
            return this;
        }

        @java.lang.Override
        @JsonSetter("workspace_id")
        public NameStage workspaceId(String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public CompanyNameStage name(String name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        @JsonSetter("company_name")
        public IsSandboxStage companyName(String companyName) {
            this.companyName = companyName;
            return this;
        }

        @java.lang.Override
        @JsonSetter("is_sandbox")
        public _FinalStage isSandbox(boolean isSandbox) {
            this.isSandbox = isSandbox;
            return this;
        }

        /**
         * <hr />
         * <pre><code>deprecated: use company_name
         * ---
         * </code></pre>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage connectPartnerName(String connectPartnerName) {
            this.connectPartnerName = Optional.of(connectPartnerName);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "connect_partner_name", nulls = Nulls.SKIP)
        public _FinalStage connectPartnerName(Optional<String> connectPartnerName) {
            this.connectPartnerName = connectPartnerName;
            return this;
        }

        @java.lang.Override
        public Workspace build() {
            return new Workspace(workspaceId, name, companyName, isSandbox, connectPartnerName, additionalProperties);
        }
    }
}
