/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.useridentities.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = UserIdentitiesListAcsSystemsRequest.Builder.class)
public final class UserIdentitiesListAcsSystemsRequest {
    private final String userIdentityId;

    private final Map<String, Object> additionalProperties;

    private UserIdentitiesListAcsSystemsRequest(String userIdentityId, Map<String, Object> additionalProperties) {
        this.userIdentityId = userIdentityId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("user_identity_id")
    public String getUserIdentityId() {
        return userIdentityId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserIdentitiesListAcsSystemsRequest
                && equalTo((UserIdentitiesListAcsSystemsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserIdentitiesListAcsSystemsRequest other) {
        return userIdentityId.equals(other.userIdentityId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.userIdentityId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UserIdentityIdStage builder() {
        return new Builder();
    }

    public interface UserIdentityIdStage {
        _FinalStage userIdentityId(String userIdentityId);

        Builder from(UserIdentitiesListAcsSystemsRequest other);
    }

    public interface _FinalStage {
        UserIdentitiesListAcsSystemsRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UserIdentityIdStage, _FinalStage {
        private String userIdentityId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UserIdentitiesListAcsSystemsRequest other) {
            userIdentityId(other.getUserIdentityId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("user_identity_id")
        public _FinalStage userIdentityId(String userIdentityId) {
            this.userIdentityId = userIdentityId;
            return this;
        }

        @java.lang.Override
        public UserIdentitiesListAcsSystemsRequest build() {
            return new UserIdentitiesListAcsSystemsRequest(userIdentityId, additionalProperties);
        }
    }
}
