/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.entrances.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import com.seam.api.types.AcsEntrance;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = EntrancesGetResponse.Builder.class)
public final class EntrancesGetResponse {
    private final AcsEntrance acsEntrance;

    private final boolean ok;

    private final Map<String, Object> additionalProperties;

    private EntrancesGetResponse(AcsEntrance acsEntrance, boolean ok, Map<String, Object> additionalProperties) {
        this.acsEntrance = acsEntrance;
        this.ok = ok;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("acs_entrance")
    public AcsEntrance getAcsEntrance() {
        return acsEntrance;
    }

    @JsonProperty("ok")
    public boolean getOk() {
        return ok;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EntrancesGetResponse && equalTo((EntrancesGetResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EntrancesGetResponse other) {
        return acsEntrance.equals(other.acsEntrance) && ok == other.ok;
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.acsEntrance, this.ok);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AcsEntranceStage builder() {
        return new Builder();
    }

    public interface AcsEntranceStage {
        OkStage acsEntrance(AcsEntrance acsEntrance);

        Builder from(EntrancesGetResponse other);
    }

    public interface OkStage {
        _FinalStage ok(boolean ok);
    }

    public interface _FinalStage {
        EntrancesGetResponse build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AcsEntranceStage, OkStage, _FinalStage {
        private AcsEntrance acsEntrance;

        private boolean ok;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(EntrancesGetResponse other) {
            acsEntrance(other.getAcsEntrance());
            ok(other.getOk());
            return this;
        }

        @Override
        @JsonSetter("acs_entrance")
        public OkStage acsEntrance(AcsEntrance acsEntrance) {
            this.acsEntrance = acsEntrance;
            return this;
        }

        @Override
        @JsonSetter("ok")
        public _FinalStage ok(boolean ok) {
            this.ok = ok;
            return this;
        }

        @Override
        public EntrancesGetResponse build() {
            return new EntrancesGetResponse(acsEntrance, ok, additionalProperties);
        }
    }
}
