/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.credentials.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.seam.api.core.ObjectMappers;
import com.seam.api.types.AcsCredential;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = CredentialsListResponse.Builder.class)
public final class CredentialsListResponse {
    private final List<AcsCredential> acsCredentials;

    private final boolean ok;

    private final Map<String, Object> additionalProperties;

    private CredentialsListResponse(
            List<AcsCredential> acsCredentials, boolean ok, Map<String, Object> additionalProperties) {
        this.acsCredentials = acsCredentials;
        this.ok = ok;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("acs_credentials")
    public List<AcsCredential> getAcsCredentials() {
        return acsCredentials;
    }

    @JsonProperty("ok")
    public boolean getOk() {
        return ok;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CredentialsListResponse && equalTo((CredentialsListResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CredentialsListResponse other) {
        return acsCredentials.equals(other.acsCredentials) && ok == other.ok;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.acsCredentials, this.ok);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OkStage builder() {
        return new Builder();
    }

    public interface OkStage {
        _FinalStage ok(boolean ok);

        Builder from(CredentialsListResponse other);
    }

    public interface _FinalStage {
        CredentialsListResponse build();

        _FinalStage acsCredentials(List<AcsCredential> acsCredentials);

        _FinalStage addAcsCredentials(AcsCredential acsCredentials);

        _FinalStage addAllAcsCredentials(List<AcsCredential> acsCredentials);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OkStage, _FinalStage {
        private boolean ok;

        private List<AcsCredential> acsCredentials = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CredentialsListResponse other) {
            acsCredentials(other.getAcsCredentials());
            ok(other.getOk());
            return this;
        }

        @java.lang.Override
        @JsonSetter("ok")
        public _FinalStage ok(boolean ok) {
            this.ok = ok;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllAcsCredentials(List<AcsCredential> acsCredentials) {
            this.acsCredentials.addAll(acsCredentials);
            return this;
        }

        @java.lang.Override
        public _FinalStage addAcsCredentials(AcsCredential acsCredentials) {
            this.acsCredentials.add(acsCredentials);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "acs_credentials", nulls = Nulls.SKIP)
        public _FinalStage acsCredentials(List<AcsCredential> acsCredentials) {
            this.acsCredentials.clear();
            this.acsCredentials.addAll(acsCredentials);
            return this;
        }

        @java.lang.Override
        public CredentialsListResponse build() {
            return new CredentialsListResponse(acsCredentials, ok, additionalProperties);
        }
    }
}
