/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.seam.api.resources.acs.credentials.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CredentialsCreateRequestVisionlineMetadataCardFunctionType {
    GUEST("guest"),

    STAFF("staff");

    private final String value;

    CredentialsCreateRequestVisionlineMetadataCardFunctionType(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
